### ISSUE TITLE
shelr setup fails on ubu 12.04 (precise)

### ISSUE THREAD

**Issue by agrabauskas** [shelr/shelr#10]
root@vger:~# shelr setup xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
/usr/local/bin/shelr:19:in `load': /var/lib/gems/1.8/gems/shelr-0.16.1/bin/shelr:52: syntax error, unexpected ':', expecting ')' (SyntaxError)
  Shelr::Recorder.record!(sound: ARGV[1] == '--sound')
                                ^
/var/lib/gems/1.8/gems/shelr-0.16.1/bin/shelr:52: syntax error, unexpected ')', expecting kEND
/var/lib/gems/1.8/gems/shelr-0.16.1/bin/shelr:55: syntax error, unexpected kWHEN, expecting $end
when 'play'
    ^
        from /usr/local/bin/shelr:19

**Comment by nashby** [comment]
@agrabauskas thanks! I've fixed it by e13d11c20ad5c1356b

**Comment by agrabauskas** [comment]
it works.

**Comment by antono** [comment]
Pushed new gem :)

**Comment by antono** [comment]
Also, @agrabauskas it's recommended to install shelr from ppa on Precise :)
I usually test it with dependencies from distro... https://launchpad.net/~antono/+archive/shelr

**Comment by agrabauskas** [comment]
yup - the first thing i did when it failed was add the ppa and try from there. still failed, so i posted the issue.

in any case - you can consider 0.16.2 test - i pulled it right after you bumped it. working fine now, afaict.

**Comment by antono** [comment]
@agrabauskas its better to remove /usr/local/bin/shelr before installation from ppa. it should work then.

**Comment by antono** [comment]
@agrabauskas thanks for reporting this :) and welcome!

**Comment by agrabauskas** [comment]
lol... DOH! i knew that. guess i just wasn't thinking.
